class Dummydb {
  static List<Map> topsearch = [
    {
      "image":
          "https://m.media-amazon.com/images/M/MV5BMjE2N2MyMzEtNmU5NS00OTI0LTlkNTMtMWM1YWYyNmU4NmY0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
      "netflixshow": "Stranger Things"
    },
    {
      "image":
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqsOWNiDIZDfXqkiWOzw8Z-z1CRNsPu58qPQ&s",
      "netflixshow": "The Witcher"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/d/d5/Professor_%28Money_Heist%29.jpg",
      "netflixshow": "Money Heist"
    },
    {
      "image":
          "https://qph.cf2.quoracdn.net/main-qimg-8a684e29c906aaf8874155af868f4a38-lq",
      "netflixshow": "Dark"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/b/b9/Narcos_season_1.png",
      "netflixshow": "Narcos"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/The_Crown_season_2.jpeg/220px-The_Crown_season_2.jpeg",
      "netflixshow": "The Crown"
    },
  ];
  static List<Map> preview = [
    {
      "image": "https://upload.wikimedia.org/wikipedia/en/b/bb/You_Season_2.jpg"
    },
    {
      "image":
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTt72KzdNv3T417ArvrxzRFv0Zwsc4jE9LwBw&s"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/b/b5/One_Piece_DVD_20.png"
    },
    {
      "image":
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqsOWNiDIZDfXqkiWOzw8Z-z1CRNsPu58qPQ&s"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/1/1d/Game_of_Thrones_Season_3.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/9/99/Vikings_Title.png"
    },
    {"image": "https://upload.wikimedia.org/wikipedia/en/d/dd/Squid_Game.jpg"},
  ];
  static List<Map> continuelist = [
    {
      "image":
          "https://m.media-amazon.com/images/M/MV5BMjE2N2MyMzEtNmU5NS00OTI0LTlkNTMtMWM1YWYyNmU4NmY0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"
    },
    {"image": "https://upload.wikimedia.org/wikipedia/en/d/dd/Squid_Game.jpg"},
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/d/d5/Professor_%28Money_Heist%29.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/b/bd/Breaking_Bad_season_four_DVD.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/b/b9/Narcos_season_1.png"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/9/99/Vikings_Title.png"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/The_Crown_season_2.jpeg/220px-The_Crown_season_2.jpeg"
    },
  ];
  static List<Map> popularlist = [
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/thumb/a/ab/Avatar_The_Last_Airbender_%282024_TV_series%29_poster.png/220px-Avatar_The_Last_Airbender_%282024_TV_series%29_poster.png"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/thumb/7/78/Suits_season_7_dvd_cover.jpg/220px-Suits_season_7_dvd_cover.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/thumb/a/aa/How_I_Met_Your_Mother_S9.jpg/250px-How_I_Met_Your_Mother_S9.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/4/4c/Kalki_2898_AD.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/b/bf/Minnal_Murali.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/d/d9/Saripodhaa_Sanivaaram.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/1/1b/Daredevil_season_1_poster.jpg"
    },
  ];
  static List<Map> trendinglist = [
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/thumb/c/cb/3_Body_Problem_%28TV_series%29.jpg/220px-3_Body_Problem_%28TV_series%29.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/thumb/a/ab/Avatar_The_Last_Airbender_%282024_TV_series%29_poster.png/220px-Avatar_The_Last_Airbender_%282024_TV_series%29_poster.png"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/thumb/c/c4/ArcaneJinx.jpeg/200px-ArcaneJinx.jpeg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/1/19/Rebel_moon_part1_poster.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/d/d9/Saripodhaa_Sanivaaram.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/2/22/The-vampire-diaries-season-2-dvd_558x754.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/4/4c/Kalki_2898_AD.jpg"
    },
  ];
  static List<Map> top10list = [
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/7/78/Stranger_Things_season_4.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/The_Witcher_s2_soundtrack.jpg/220px-The_Witcher_s2_soundtrack.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/thumb/1/15/The_Sandman_s1_soundtrack.jpg/220px-The_Sandman_s1_soundtrack.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/thumb/9/98/Shadow_and_Bone_%28soundtrack%29.jpg/220px-Shadow_and_Bone_%28soundtrack%29.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/d/d9/Saripodhaa_Sanivaaram.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/thumb/8/82/Maharaja_2024_film_poster.jpg/220px-Maharaja_2024_film_poster.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/b/bf/Minnal_Murali.jpg"
    },
  ];
  static List<Map> mylist = [
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/b/bf/Minnal_Murali.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/7/78/Stranger_Things_season_4.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/4/41/Tumbbad_poster.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/d/da/DarkNetflixPosterEnglish.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/4/4c/Deadpool_%26_Wolverine_poster.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/The_Witcher_s2_soundtrack.jpg/220px-The_Witcher_s2_soundtrack.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/d/d5/Professor_%28Money_Heist%29.jpg"
    },
  ];
  static List<Map> indianmovieslist = [
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/thumb/8/82/Maharaja_2024_film_poster.jpg/220px-Maharaja_2024_film_poster.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/d/d9/Saripodhaa_Sanivaaram.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/b/bf/Minnal_Murali.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/4/41/Tumbbad_poster.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/f/fb/The_Goat_Life_poster.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/thumb/7/75/Leo_%282023_Indian_film%29.jpg/220px-Leo_%282023_Indian_film%29.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/d/d0/K.G.F_Chapter_2.jpg"
    },
  ];
  static List<Map> hollywoodmtvlist = [
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/thumb/c/cb/3_Body_Problem_%28TV_series%29.jpg/220px-3_Body_Problem_%28TV_series%29.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/9/9b/Blade_Runner_2049_poster.png"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/6/64/Cobra_Kai_season_4_promotional_poster.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/5/59/1899NetflixPosterEnglish.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/e/e1/Joker_%282019_film%29_poster.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/5/59/The_Gray_Man_poster.png"
    },
  ];
  static List<Map> originalslist = [
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/thumb/e/e8/RagnarokArt.jpg/220px-RagnarokArt.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/5/59/The_Gray_Man_poster.png"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/thumb/b/bb/You_Season_2.jpg/220px-You_Season_2.jpg"
    },
    {"image": "https://upload.wikimedia.org/wikipedia/en/4/46/Bulbbul.jpg"},
    {"image": "https://upload.wikimedia.org/wikipedia/en/d/dd/Squid_Game.jpg"},
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/d/dd/Rebel_Moon_%E2%80%93_Part_Two_The_Scargiver_poster.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/6/64/Cobra_Kai_season_4_promotional_poster.jpg"
    },
  ];
  static List<Map> watchagainlist = [
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/1/19/Rebel_moon_part1_poster.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/f/ff/The_Batman_%28film%29_poster.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/8/82/Army_of_the_Dead_poster.png"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/5/52/Laapataa_Ladies_poster.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/5/5b/Vincenzo_TV_series.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/thumb/7/75/Alice_in_Borderland_poster.jpg/220px-Alice_in_Borderland_poster.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/0/0b/Your_Name_poster.png"
    },
  ];
  static List<Map> newlist = [
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/b/bb/Vikings_Valhalla_logo.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/thumb/a/a7/Venom_Let_There_Be_Carnage_poster.jpg/220px-Venom_Let_There_Be_Carnage_poster.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/thumb/7/7d/Gyeongseong_Creature_poster.png/220px-Gyeongseong_Creature_poster.png"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/a/a8/TokyoRevengersSeason1.jpg"
    },
    {
      "image":
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZ94toUpWPo-I2mOtnJQewDa0WxyNhP_3Bxw&s"
    },
    {"image": "https://upload.wikimedia.org/wikipedia/en/0/05/My_Demon.jpg"},
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/e/e9/Castlevania_Nocturne_Season_1_%282023%29_poster.jpg"
    },
  ];
  static List<Map> showindianlist = [
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/e/ed/Navarasa_web_series.jpg",
      "Showname": ""
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/thumb/a/a3/Betaal_logo.jpg/220px-Betaal_logo.jpg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/hi/f/f4/Delhi_Crime_poster.jpeg"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/2/2f/Kaala_Paani_poster.png"
    },
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/a/a8/The_Railway_Men_Poster.jpg"
    },
    {"image": "https://upload.wikimedia.org/wikipedia/en/0/07/Rana_Naidu.jpg"},
    {
      "image":
          "https://upload.wikimedia.org/wikipedia/en/a/a7/The_Hunt_for_Veerappan_poster.jpeg"
    },
  ];
}
